"""
Pydantic schemas for MailTraceAI Evidence-Grounded Investigation Copilot.
Enforces structured evidence grounding, explicit uncertainty levels, prompt-injection isolation,
and non-destructive SOC action suggestions.
"""
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class CopilotMode(str, Enum):
    EMAIL = "email"
    CASE = "case"
    CAMPAIGN = "campaign"


class UncertaintyLevel(str, Enum):
    CONFIRMED = "CONFIRMED"
    HIGH_CONFIDENCE_INFERENCE = "HIGH-CONFIDENCE INFERENCE"
    PROBABLE = "PROBABLE"
    LOW_CONFIDENCE_HYPOTHESIS = "LOW-CONFIDENCE HYPOTHESIS"
    UNKNOWN = "UNKNOWN"


class EvidenceReference(BaseModel):
    """
    Forensic evidence item grounding a statement generated by the copilot.
    Maps back to a specific stored Evidence ID (e.g., E-1042).
    """
    evidence_id: str = Field(..., description="Canonical evidence identifier (e.g. E-1042, EV-GEO-1)")
    type: str = Field(..., description="Evidence category (e.g. authentication, relay, lookalike, url, attachment, campaign, ip)")
    statement: str = Field(..., description="Empirical forensic observation or proof")
    source_module: str = Field("forensic_engine", description="Module that generated this evidence")
    reliability: float = Field(0.9, ge=0.0, le=1.0, description="Reliability score of source")
    confidence_category: str = Field("CONFIRMED", description="Certainty classification of this finding")
    raw_data: Optional[Dict[str, Any]] = Field(default=None, description="Optional supporting forensic properties")


class CopilotActionType(str, Enum):
    VIEW_EVIDENCE = "view_evidence"
    OPEN_GRAPH = "open_graph"
    COMPARE_EMAILS = "compare_emails"
    ADD_TO_CASE = "add_to_case"
    GENERATE_REPORT = "generate_report"
    INVESTIGATE_DOMAIN = "investigate_domain"


class CopilotAction(BaseModel):
    """
    Actionable recommendation suggested by the copilot.
    Must be explicitly triggered by analyst interaction; never auto-executed destructively.
    """
    action_type: CopilotActionType = Field(..., description="Action category")
    label: str = Field(..., description="User-facing button label")
    description: Optional[str] = Field(None, description="Explanation of what this action does")
    params: Dict[str, Any] = Field(default_factory=dict, description="Contextual parameters for execution")


class SuggestedQuestion(BaseModel):
    """
    Context-tailored suggested investigation prompt.
    """
    question: str = Field(..., description="Suggested natural language question")
    category: str = Field(..., description="Question domain (e.g. threat_score, attribution, campaign, auth)")
    mode: CopilotMode = Field(..., description="Applicable investigation mode")


class CopilotQueryRequest(BaseModel):
    """
    Natural language query request to the Investigation Copilot.
    """
    query: str = Field(..., description="Analyst's natural language question")
    mode: CopilotMode = Field(CopilotMode.EMAIL, description="Active investigation mode: email, case, or campaign")
    context_id: Optional[str] = Field(None, description="Target entity ID: email_id, case_id, or campaign_id")
    email_payload: Optional[Dict[str, Any]] = Field(None, description="Optional raw or analyzed email payload for ad-hoc inspection")
    include_timeline: bool = Field(True, description="Whether to include attack timeline events in context")
    user: Optional[str] = Field("SOC Analyst", description="Analyst username for audit logging")


class CopilotQueryResponse(BaseModel):
    """
    Evidence-grounded response from the Investigation Copilot.
    """
    query: str = Field(..., description="Original analyst query")
    mode: CopilotMode = Field(..., description="Investigation mode evaluated")
    context_id: Optional[str] = Field(None, description="Associated context identifier")
    assessment: str = Field(..., description="Concise, direct answer to the analyst question")
    reasoning_summary: str = Field(..., description="Evidence-based reasoning summary (no hidden chain-of-thought)")
    confidence: UncertaintyLevel = Field(..., description="Explicit calibrated uncertainty level")
    evidence_refs: List[EvidenceReference] = Field(default_factory=list, description="Grounding evidence records with IDs")
    suggested_actions: List[CopilotAction] = Field(default_factory=list, description="Prescriptive, non-destructive SOC actions")
    recommended_next_steps: List[str] = Field(default_factory=list, description="Next investigative steps for the analyst")
    model: str = Field("mailtrace-copilot-v1", description="Model or service identifier used")
    timestamp: str = Field(..., description="ISO timestamp of copilot inference")
    audit_id: Optional[str] = Field(None, description="Reference ID in audit trail")


class CopilotAddToReportRequest(BaseModel):
    """
    Request to append copilot-generated findings to an investigation report.
    """
    case_id: Optional[str] = Field(None, description="Associated Case ID")
    report_id: Optional[str] = Field(None, description="Existing Report ID if updating")
    email_id: Optional[str] = Field(None, description="Associated Email ID")
    query: str = Field(..., description="Analyst query that led to summary")
    summary_text: str = Field(..., description="Copilot assessment & reasoning summary to incorporate")
    evidence_ids: List[str] = Field(default_factory=list, description="Associated Evidence IDs grounding the summary")
    confidence: UncertaintyLevel = Field(UncertaintyLevel.PROBABLE, description="Recorded confidence level")
    model: str = Field("mailtrace-copilot-v1", description="Model used for the summary")
    analyst_name: str = Field("SOC Analyst", description="Analyst submitting the summary")


class CopilotAuditLogResponse(BaseModel):
    """
    Audit log entry for a Copilot query.
    """
    id: str
    user: str
    query: str
    mode: str
    context_id: Optional[str] = None
    evidence_ids: List[str]
    confidence: str
    model_identifier: str
    timestamp: str
